version: '3'
services:
  redis:
    build: db
    ports:
     - "6379:6379"
    volumes:
     - ./db/data/:/var/lib/redis/
  injector:
    build: injector
    depends_on:
     - "redis"
    environment:
      REDIS_CLI: "redis-cli -h HOST" # testing site